services:
  api:
    build:
      context: .  
      dockerfile: Dockerfile
    container_name: flask_api_container
    ports:
      - "${API_PORT:-5000}:5000" 
    environment:
      - FLASK_ENV=development 
      - API_PORT=5000
    volumes:
      - .:/app # Mount mã nguồn từ local vào container
    working_dir: /app
    command: flask run --host=0.0.0.0 --port=5000